version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - '5678:5678'
    environment:
      N8N_HOST: automation.naukaridarpan.com
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      WEBHOOK_URL: https://automation.naukaridarpan.com/
      GENERIC_TIMEZONE: Asia/Kolkata
      N8N_SECURE_COOKIE: 'true'
      N8N_RUNNERS_ENABLED: 'true'
      DB_TYPE: sqlite
      DB_SQLITE_DATABASE: /home/node/.n8n/database.sqlite
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
